---
- name: update codedeploy config file
  hosts: localhost
  gather_facts: no
  become: true

  tasks:
    - name: updating codedeploy config
      copy:
        dest: "/etc/codedeploy-agent/conf/codedeployagent.yml"
        content: |
          ---
          :log_aws_wire: false
          :log_dir: '/var/log/aws/codedeploy-agent/'
          :pid_dir: '/opt/codedeploy-agent/state/.pid/'
          :program_name: codedeploy-agent
          :root_dir: '/opt/codedeploy-agent/deployment-root'
          :verbose: false
          :wait_between_runs: 1
          :proxy_uri:
          :max_revisions: 5
          :disable_imds_v1: false
          :proxy_uri: 'http://172.31.21.180:3128/'

